service:
  type: LoadBalancer
  annotations:
    # AWS LBC annotations to tell it to create an NLB
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

ports:
  web:
    port: 80
    redirectTo:
      port: 443
  websecure:
    port: 443

dashboard:
  enabled: true 

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure