clusterName: gitea-eks-cluster
region: eu-west-2
vpcId: vpc-0bfc3e0ed7fce8f8d

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::727646481331:role/gitea-eks-platform-load-balancer-controller-role"