gitea:
  admin:
    username: gitea_admin
    existingSecret: gitea-admin-secret
    email: "hasan-kamran@outlook.com"

  config:
    database:
      DB_TYPE: postgres
      HOST: "terraform-cd4b439913c48d0ff35c9fc7f4.cdgy426y6dv1.eu-west-2.rds.amazonaws.com:5432"
      NAME: eks_gitea_db
      USER: gitea_user
      SSL_MODE: require
    APP_NAME: "Gitea: Git with a cup of tea"

  additionalConfigFromEnvs:
    - name: GITEA__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: gitea-db-secret
          key: password
  
image:
  registry: 727646481331.dkr.ecr.eu-west-2.amazonaws.com
  repository: gitea-eks-platform-gitea
  tag: "1.27.1-rootless"
  rootless: false

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-gitea
  tls:
    - secretName: gitea-tls
      hosts:
       - gitea.hasanenv.co.uk
  hosts:
    - host: gitea.hasanenv.co.uk
      paths:      
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  size: 10Gi

postgresql:
  enabled: false

postgresql-ha:
  enabled: false